version: '3'

services:
  web:
    build: .
    image: mangofi/web:latest
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.development.local

volumes:
  node_modules: