export const SET_ACCOUNT = 'WALLET.SET_ACCOUNT';
export const SET_NETWORK_ID = 'WALLET.SET_NETWORK_ID';
export const SET_BALANCES = 'WALLET.SET_BALANCES';
export const UPDATE_BALANCE = 'WALLET.UPDATE_BALANCE';
